### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lxianl455** [yhit98/FITE#1]
Where can i get the data?

**Comment by lxianl455** [comment]
我下载了IJCAI2019_data的那个数据集。但是运行结果和论文中的结果差很多。
我实验Twitter2017的数据集，最后得到的只有：
AVERAGE ACC = 0.6889789303079417
AVERAGE MAC-F1= 0.6618514109412116
应该怎么复现论文中提到的：ACC  73.87  MAC 73.03的结果？

**Comment by yhit98** [comment]
I think you need to change the code in FITE.py: PRE_TRAINED_MODEL_NAME = "bert-base-uncased" to PRE_TRAINED_MODEL_NAME = "vinai/bertweet-large" , and adjust the learning rate.

**Comment by h-aboutalebi** [comment]
Where can I get the dataset? There is no instruction on how to obtain the dataset for Twitter-2017.

**Comment by yhit98** [comment]
You can download the twitter-2017 dataset here:https://github.com/jefferyYu/TomBERT/tree/master/absa_data/twitter,
twitter-2015 dataset here:https://github.com/jefferyYu/TomBERT/tree/master/absa_data/twitter2015, and you can find the images in the TomBERT repo: https://github.com/jefferyYu/TomBERT#download-tweet-images-and-set-up-image-path.
